apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginxreloder
  annotations:
    # (1)
    secret.reloader.stakater.com/reload: "secure-callme-cert"
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
